### PR TITLE
feat: add support for JSON logging

### PR DESCRIPTION
**Pull request by Fox32**
You can activate JSON logging for normal log messages and request log via the ENABLE_JSON_LOGGING environment variable.

### CODE REVIEW

**Comment by dhenneke** [comment]
I tested it and I like it. Do we care about the sonar issues?

**Comment by JoergSiebahn** [comment]
> I tested it and I like it. Do we care about the sonar issues?

I think we can close the "extract constant" issues as Won't Fix in Sonarcloud.
We may wan't to fix the code duplication and give the method a more generic name like `createConsoleAppender`.

**Comment by JoergSiebahn** [comment]
Maybe we can involve @wurstbrot to resolve the security hotspots of sda-dropwizard-commons explicitly?

**Comment by Fox32** [comment]
> I think we can close the "extract constant" issues as Won't Fix in Sonarcloud.
> We may wan't to fix the code duplication and give the method a more generic name like `createConsoleAppender`.

After looking at it, I would close all three. Refactoring the duplicated code would just bloat it up.

**Comment by wurstbrot** [comment]
Thank you for considering security in your daily work!

The issue mentioned is that by using env. variables, an attacker might inject something. Therefore, env variables should be compared against a whitelist or at least sanitized.

The following condition is used:
_"true".equals(System.getenv("ENABLE_JSON_LOGGING")_
This is good from a security standpoint because a whitelist (with value "true") is defined and compared against.

**Pull request merged**
