### PR TITLE
Simplify CSP and add sandbox

### PR DESCRIPTION
**Pull request by wurstbrot**
Hardening is important. This PRs improves the header security for an api endpoint:
- simplify CSP
- adding sandbox
according to "API Security in Action" page 58.

Complications with frontend applications like angular are not expected.
In case HTML applications are delivered to the client directly, it will infect for example javascript execution.

### CODE REVIEW

**Comment by christopher-cudennec** [comment]
ping @wurstbrot

**Comment by wurstbrot** [comment]
I am not having the dropwizard insights to implement the advanced requirements.

**Comment by christopher-cudennec** [comment]
@JoergSiebahn / @wurstbrot : Are you aware of any application that server static files / use dropwizard-views?

**Comment by christopher-cudennec** [comment]
@kairabiensda : Could you also have a look at the CSP change and the potential effects?

**Comment by christopher-cudennec** [comment]
@wurstbrot : I squashed your commits and used spotless to apply our code formatting rules.

**Comment by JoergSiebahn** [comment]
Services that serve simple server side rendered UIs (where an additional app is way too much) will not work any more. To make it backward compatible this change should be a configurable option. It may be suitable to use this change as a new default but have a config option to restore the old behavior and add an information to the release notes how to activate it.

Another question:
Will this only affect resources served by the service or also involved apps on the same domain? We have cases where we expose single page apps from nginx based images and APIs from services on the same domain by using the same Ingress proxy. Will such scenarios be affected?

**Comment by JoergSiebahn** [comment]
We also found [a discussion on Stackoverflow](https://stackoverflow.com/q/45630376), where the use of CSP for APIs are questioned:

> It's mainly to appease infosec.

> Practically, the advantages may be slim to none.

**Comment by JoergSiebahn** [comment]
@wurstbrot @christopher-cudennec please see #1641 for configuration option. It is built on top of this PR.

**Pull request closed without merging**
