### PR TITLE
docs: Deprecation for server-starter + server-swagger

### PR DESCRIPTION
**Pull request by christopher-cudennec**
Please use sda-commons-starter + sda-commons-server-openapi instead.

### CODE REVIEW

**Review by JoergSiebahn — COMMENTED** [review]
What about the classes?
- https://github.com/SDA-SE/sda-dropwizard-commons/blob/master/sda-commons-server-starter/src/main/java/org/sdase/commons/server/starter/SdaPlatformBundle.java
- https://github.com/SDA-SE/sda-dropwizard-commons/blob/master/sda-commons-server-swagger/src/main/java/org/sdase/commons/server/swagger/SwaggerBundle.java

**Comment by christopher-cudennec** [comment]
I added deprecation warnings to the classes. 👍

**Review by JoergSiebahn — APPROVED** [review]

**Comment by christopher-cudennec** [comment]
Ok to disable the "SonarCloud" check for this PR?

**Comment by JoergSiebahn** [comment]
> Ok to disable the "SonarCloud" check for this PR?

Yes, of course. The „Code Smell“ is actually good communication in this case.

**Pull request merged**
