### PR TITLE
Update PolicyExistsHealthCheck.java

### PR DESCRIPTION
**Pull request by andreas-trenkmann**
A client post request leads to a warning by OPA-Agent, when FAIL_ON_UNKOWN_PROPERTIES is set by SPI this call will result in an exception. A GET-call solves this conflict.

### CODE REVIEW

**Comment by christopher-cudennec** [comment]
Hi @andreas-trenkmann and thanks for your PR!

I think I got your point for the PR. At the moment Spotless and tests are failing.

I think we need to compare [the official documentation](https://www.openpolicyagent.org/docs/latest/rest-api/#get-a-document) if your change is still a valid request. At the first glance, I assume that this is the case.

I will also try it out locally using an image of the OpenPolicyAgent.

Cheers,

Christopher

**Comment by christopher-cudennec** [comment]
When using `opa run --ignore=.* --server --log-level=debug -w /policies`  I don't see exceptions or errors in the log.

* can you give us the startup flags / configuration of your OPA sidecar to reproduce the behaviour?
* can you give us the OPA version you're using?

Thanks!

**Comment by andreas-trenkmann** [comment]
Hi https://github.com/christopher-cudennec,

we are using a common SI-opa-image, the version in this image is 0.39.0.

OPA-Logs (path is cutted for security reasons):
response.","req_id":3,"req_method":"POST","req_path":"/v1/data/de/...","resp_body":"{\"result\":{\"allow\":false,\"allowedPathsWithoutToken\":[[\"contract\"]]},\"warning\":{\"code\":\"api_usage_warning\",\"message\":\"'input' key missing from the request\"}}","resp_bytes":156,"resp_duration":0.9203,"resp_status":200,"time":"2023-01-26T12:38:13+01:00"}

The health check will fail by activating the following setting for Object-Mapper: objectMapper.enable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)

**Comment by christopher-cudennec** [comment]
Hi @andreas-trenkmann!

I wonder how you setup your application, because we [explicitly disable that feature](https://github.com/SDA-SE/sda-dropwizard-commons/blob/913713380fb94a523f06ad5593426e408c8309e6/sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/ObjectMapperConfigurationUtil.java#L159) to implement the "tolerant reader" pattern. Is there a concrete use case why you need it?

If you need a different ObjectMapper with a different configuration you can create a new one that suits your requirements.

Cheers, 

Christopher

**Comment by andreas-trenkmann** [comment]
Hi Christopher,

as mentioned in my initial comment some SPI - extensions (Service Provider Interface) by extern dependencies may explicit disable this feature regardless the settings you have been set.

Please change the call to a GET for a clean solution, as mentioned in your own comment: https://github.com/SDA-SE/sda-dropwizard-commons/blob/913713380fb94a523f06ad5593426e408c8309e6/sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/health/PolicyExistsHealthCheck.java#L26

best regards 

Andreas

**Comment by christopher-cudennec** [comment]
Hi @andreas-trenkmann !

Would you like to contribute your changes to our project? We have a [short description](https://github.com/SDA-SE/sda-dropwizard-commons/blob/master/CONTRIBUTING.md) what you should consider when making code changes. As you might see, actions are failing at the moment. I guess you'd need to

* run the code formatter: `./gradlew spotlessApply`
* make the tests run successfully again

We're happy to guide you through the procedure and help you get to know our library.

Just last one last comment:
> as mentioned in my initial comment some SPI - extensions (Service Provider Interface) by extern dependencies may explicit disable this feature regardless the settings you have been set.

We (and AFAIK also Signal Iduna) always advocate the tolerant reader pattern. It is a very important principle of all SDA services.

Cheers,

Christopher

**Comment by elbiocaetano** [comment]
Since we had no answer from the contributor, we opened a new PR with the requested changed
https://github.com/SDA-SE/sda-dropwizard-commons/pull/2114

**Pull request closed without merging**
