### PR TITLE
fix(server-jackson): support nullable query params in the HalLinkProvider

### PR DESCRIPTION
**Pull request by jeskosda**
In some cases it could be required that the QueryParam is nullable. Maybe you want to link to a specific set of entities which are prefiltered?

```
    URI uri = linkTo(methodOn(MedicalHistoryService.class).getEvents("12345", null, null, null, null, null, null)).asUri();
    assertThat(uri).hasPath("/medicalEvents").hasParameter("insuredPersonId", "12345");
    assertThat(uri.toString()).isEqualTo("/medicalEvents?insuredPersonId=12345");
```

### CODE REVIEW

**Comment by dhenneke** [comment]
`fix(server-jackson): support nullable query params in the HALLinkProvider`?

**Comment by jeskosda** [comment]
Changed the commit message. I was not aware of the right message pattern.

**Comment by dhenneke** [comment]
We usually use the last part of the module name that is changed as scope. In this case sda-commons-**server-jackson**.

**Comment by Fox32** [comment]
> I was not aware of the right message pattern.

See the [contributing guidelines](https://github.com/SDA-SE/sda-dropwizard-commons/blob/master/CONTRIBUTING.md) with some examples.

**Review by dhenneke — APPROVED** [review]

**Pull request merged**
